# SPDX-FileCopyrightText: Copyright (c) 2025 Objectionary.com
# SPDX-License-Identifier: MIT

[files]
extend-exclude = [
  'fourmolu.yaml'
]

[default]
extend-ignore-identifiers-re = [
  "ASS*"       # false positive
  "bimap"      # false positive
]
