# SPDX-FileCopyrightText: Copyright (c) 2025 Objectionary.com
# SPDX-License-Identifier: MIT
# yamllint disable rule:line-length
---
phi: |
  Q -> [[
    foo -> [[
      @ -> $.^.z,
      bar -> Q.y(5, "foo")
    ]]
  ]]
xpaths:
  - '/object/o[@name="foo" and o[2][contains(@base,".y")]]'
  - '/object/o/o/o[@as="α0" and contains(@base,"org.eolang.number")]'
  - '/object/o/o/o[@as="α1" and contains(@base,"org.eolang.string")]'
  - '/object/o/o[@name="φ" and contains(@base,".z")]'
