# SPDX-FileCopyrightText: Copyright (c) 2025 Objectionary.com
# SPDX-License-Identifier: MIT
# yamllint disable rule:line-length
---
phi: |
  Q -> [[
    foo -> [[
      @ -> $.^.z,
      bar -> Q.y(5, "foo")
    ]]
  ]]
xpaths:
  - '/object/o[@name="foo" and o[2][@base="Φ.y"]]'
  - '/object/o/o/o[@as="α0" and @base="Φ.number"]'
  - '/object/o/o/o[@as="α1" and @base="Φ.string"]'
  - '/object/o/o[@name="φ" and @base="ξ.ρ.z"]'
