# SPDX-FileCopyrightText: Copyright (c) 2025 Objectionary.com
# SPDX-License-Identifier: MIT
# yamllint disable rule:line-length
---
program: |
  {[[ x -> Q.y(1, 2) ]]}
result: |-
  Φ ↦ ⟦
    x ↦ Φ.y(
      α0 ↦ Φ.number(
        α0 ↦ Φ.bytes(
          α0 ↦ ⟦
            Δ ⤍ 3F-F0-00-00-00-00-00-00,
            ρ ↦ ∅
          ⟧
        )
      )
    )(
      α1 ↦ Φ.number(
        α0 ↦ Φ.bytes(
          α0 ↦ ⟦
            Δ ⤍ 40-00-00-00-00-00-00-00,
            ρ ↦ ∅
          ⟧
        )
      )
    ),
    ρ ↦ ∅
  ⟧
