# SPDX-FileCopyrightText: Copyright (c) 2025 Objectionary.com
# SPDX-License-Identifier: MIT
# yamllint disable rule:line-length
---
program: |
  {[[ x -> Q.y(z -> "hey", b -> 1) ]]}
result: |-
  Φ ↦ ⟦
    x ↦ Φ.y(
      z ↦ Φ.string(
        α0 ↦ Φ.bytes(
          α0 ↦ ⟦
            Δ ⤍ 68-65-79,
            ρ ↦ ∅
          ⟧
        )
      )
    )(
      b ↦ Φ.number(
        α0 ↦ Φ.bytes(
          α0 ↦ ⟦
            Δ ⤍ 3F-F0-00-00-00-00-00-00,
            ρ ↦ ∅
          ⟧
        )
      )
    ),
    ρ ↦ ∅
  ⟧
